;;;; ultraELF 0.0.1
;;;
;;; ultraELF x86-64 assembler, disassembler and metamorphic engine.
;;; ultraELF packs and reconstructs ELF executables, maintaining original functionality.

(in-package :ultraelf)

(defun f2xm1-x87 (&rest args)
  (list #xd9 #xf0))
(defun fabs-x87 (&rest args)
  (list #xd9 #xe1))
(defun fchs-x87 (&rest args)
  (list #xd9 #xe0))
(defun fclex-x87 (&rest args)
  (list #x9b #xdb #xe2))
(defun fnclex-x87 (&rest args)
  (list #xdb #xe2))
(defun fcos-x87 (&rest args)
  (list #xd9 #xff))
(defun fdecstp-x87 (&rest args)
  (list #xd9 #xf6))
(defun fincstp-x87 (&rest args)
  (list #xd9 #xf7))
(defun finit-x87 (&rest args)
  (list #x9b #xdb #xe3))
(defun fld1-x87 (&rest args)
  (list #xd9 #xe8))
(defun fldl2e-x87 (&rest args)
  (list #xd9 #xea))
(defun fldl2t-x87 (&rest args)
  (list #xd9 #xe9))
(defun fldlg2-x87 (&rest args)
  (list #xd9 #xec))
(defun fldln2-x87 (&rest args)
  (list #xd9 #xed))
(defun fldpi-x87 (&rest args)
  (list #xd9 #xeb))
(defun fldz-x87 (&rest args)
  (list #xd9 #xee))
(defun fninit-x87 (&rest args)
  (list #xdb #xe3))
(defun fnop-x87 (&rest args)
  (list #xd9 #xd0))
(defun fpatan-x87 (&rest args)
  (list #xd9 #xf3))
(defun fprem-x87 (&rest args)
  (list #xd9 #xf8))
(defun fprem1-x87 (&rest args)
  (list #xd9 #xf5))
(defun fptan-x87 (&rest args)
  (list #xd9 #xf2))
(defun frndint-x87 (&rest args)
  (list #xd9 #xfc))
(defun fscale-x87 (&rest args)
  (list #xd9 #xfd))
(defun fsin-x87 (&rest args)
  (list #xd9 #xfe))
(defun fsincos-x87 (&rest args)
  (list #xd9 #xfb))
(defun fsqrt-x87 (&rest args)
  (list #xd9 #xfa))
(defun ftst-x87 (&rest args)
  (list #xd9 #xe4))
(defun fxam-x87 (&rest args)
  (list #xd9 #xe5))
(defun fxtract-x87 (&rest args)
  (list #xd9 #xf4))
(defun fyl2x-x87 (&rest args)
  (list #xd9 #xf1))
(defun fyl2xp1-x87 (&rest args)
  (list #xd9 #xf9))
