;;;; ultraELF 0.0.1
;;;
;;; ultraELF x86-64 assembler, disassembler and metamorphic engine.
;;; ultraELF packs and reconstructs ELF executables, maintaining original functionality.

(in-package :ultraelf)

(defparameter *emit-function-hash-table-x64* (make-hash-table :test 'equalp))
;;; segment registers.
(setf (gethash "cs:"     *emit-function-hash-table-x64*) (list #'cs-x86))
(setf (gethash "ds:"     *emit-function-hash-table-x64*) (list #'ds-x86))
(setf (gethash "es:"     *emit-function-hash-table-x64*) (list #'es-x86))
(setf (gethash "fs:"     *emit-function-hash-table-x64*) (list #'fs-x86))
(setf (gethash "gs:"     *emit-function-hash-table-x64*) (list #'gs-x86))
(setf (gethash "ss:"     *emit-function-hash-table-x64*) (list #'ss-x86))

;;; instructions in alphabetical order.
(setf (gethash "clc"     *emit-function-hash-table-x64*) (list #'clc-x86))
(setf (gethash "cld"     *emit-function-hash-table-x64*) (list #'cld-x86))
(setf (gethash "cli"     *emit-function-hash-table-x64*) (list #'cli-x86))
(setf (gethash "cmc"     *emit-function-hash-table-x64*) (list #'cmc-x86))
(setf (gethash "cmpsb"   *emit-function-hash-table-x64*) (list #'cmpsb-x86))
(setf (gethash "cmpsd"   *emit-function-hash-table-x64*) (list #'cmpsd-x32-x64))
(setf (gethash "cmpsq"   *emit-function-hash-table-x64*) (list #'cmpsq-48-x64 #'cmpsq-49-x64 #'cmpsq-4a-x64 #'cmpsq-4b-x64 #'cmpsq-4c-x64 #'cmpsq-4d-x64 #'cmpsq-4e-x64 #'cmpsq-4f-x64))
(setf (gethash "cmpsw"   *emit-function-hash-table-x64*) (list #'cmpsw-x86))
(setf (gethash "dec"     *emit-function-hash-table-x64*) (list #'dec-x64))
(setf (gethash "hlt"     *emit-function-hash-table-x64*) (list #'hlt-x86))
(setf (gethash "in"      *emit-function-hash-table-x64*) (list #'in-x32-x64))
(setf (gethash "inc"     *emit-function-hash-table-x64*) (list #'inc-x64))
(setf (gethash "insb"    *emit-function-hash-table-x64*) (list #'insb-x86))
(setf (gethash "insd"    *emit-function-hash-table-x64*) (list #'insd-x32-x64))
(setf (gethash "insw"    *emit-function-hash-table-x64*) (list #'insw-x86))
(setf (gethash "lodsb"   *emit-function-hash-table-x64*) (list #'lodsb-x86))
(setf (gethash "lodsd"   *emit-function-hash-table-x64*) (list #'lodsd-x32-x64))
(setf (gethash "lodsq"   *emit-function-hash-table-x64*) (list #'lodsq-48-x64 #'lodsq-49-x64 #'lodsq-4a-x64 #'lodsq-4b-x64 #'lodsq-4c-x64 #'lodsq-4d-x64 #'lodsq-4e-x64 #'lodsq-4f-x64))
(setf (gethash "lodsw"   *emit-function-hash-table-x64*) (list #'lodsw-x86))
(setf (gethash "neg"     *emit-function-hash-table-x64*) (list #'neg-x64))
(setf (gethash "nop"     *emit-function-hash-table-x64*) (list #'nop-x86))
(setf (gethash "rep"     *emit-function-hash-table-x64*) (list #'rep-repz-x32-x64))
(setf (gethash "repe"    *emit-function-hash-table-x64*) (list #'rep-repz-x32-x64))
(setf (gethash "repne"   *emit-function-hash-table-x64*) (list #'repnz-x32-x64))
(setf (gethash "repnz"   *emit-function-hash-table-x64*) (list #'repnz-x32-x64))
(setf (gethash "repz"    *emit-function-hash-table-x64*) (list #'rep-repz-x32-x64))
(setf (gethash "out"     *emit-function-hash-table-x64*) (list #'out-x32-x64))
(setf (gethash "outsb"   *emit-function-hash-table-x64*) (list #'outsb-x86))
(setf (gethash "outsd"   *emit-function-hash-table-x64*) (list #'outsd-x32-x64))
(setf (gethash "outsw"   *emit-function-hash-table-x64*) (list #'outsw-x86))
(setf (gethash "pop"     *emit-function-hash-table-x64*) (list #'pop-x64))
(setf (gethash "push"    *emit-function-hash-table-x64*) (list #'push-x64))
(setf (gethash "scasb"   *emit-function-hash-table-x64*) (list #'scasb-x86))
(setf (gethash "scasd"   *emit-function-hash-table-x64*) (list #'scasd-x32-x64))
(setf (gethash "scasq"   *emit-function-hash-table-x64*) (list #'scasq-48-x64 #'scasq-49-x64 #'scasq-4a-x64 #'scasq-4b-x64 #'scasq-4c-x64 #'scasq-4d-x64 #'scasq-4e-x64 #'scasq-4f-x64))
(setf (gethash "scasw"   *emit-function-hash-table-x64*) (list #'scasw-x86))
(setf (gethash "stc"     *emit-function-hash-table-x64*) (list #'stc-x86))
(setf (gethash "std"     *emit-function-hash-table-x64*) (list #'std-x86))
(setf (gethash "sti"     *emit-function-hash-table-x64*) (list #'sti-x86))
(setf (gethash "stosb"   *emit-function-hash-table-x64*) (list #'stosb-x86))
(setf (gethash "stosd"   *emit-function-hash-table-x64*) (list #'stosd-x32-x64))
(setf (gethash "stosq"   *emit-function-hash-table-x64*) (list #'stosq-48-x64 #'stosq-49-x64 #'stosq-4a-x64 #'stosq-4b-x64 #'stosq-4c-x64 #'stosq-4d-x64 #'stosq-4e-x64 #'stosq-4f-x64))
(setf (gethash "stosw"   *emit-function-hash-table-x64*) (list #'stosw-x86))
(setf (gethash "syscall" *emit-function-hash-table-x64*) (list #'syscall-x64))
(setf (gethash "movsb"   *emit-function-hash-table-x64*) (list #'movsb-x86))
(setf (gethash "movsd"   *emit-function-hash-table-x64*) (list #'movsd-x32-x64))
(setf (gethash "movsq"   *emit-function-hash-table-x64*) (list #'movsq-48-x64 #'movsq-49-x64 #'movsq-4a-x64 #'movsq-4b-x64 #'movsq-4c-x64 #'movsq-4d-x64 #'movsq-4e-x64 #'movsq-4f-x64))
(setf (gethash "movsw"   *emit-function-hash-table-x64*) (list #'movsw-x86))
