;;;; ultraELF 0.0.1
;;;
;;; ultraELF x86-64 assembler, disassembler and metamorphic engine.
;;; ultraELF packs and reconstructs ELF executables, maintaining original functionality.

(in-package :ultraelf)

(defparameter *emit-function-hash-table-x64* (make-hash-table :test 'equalp))
;;; pseudo-ops.
(setf (gethash "align"              *emit-function-hash-table-x64*) (list #'align-pseudo-op))
(setf (gethash "db"                 *emit-function-hash-table-x64*) (list #'db))
(setf (gethash "dw"                 *emit-function-hash-table-x64*) (list #'dw))
(setf (gethash "dd"                 *emit-function-hash-table-x64*) (list #'dd))
(setf (gethash "dq"                 *emit-function-hash-table-x64*) (list #'dq))
(setf (gethash "bits"               *emit-function-hash-table-x64*) (list #'bits-pseudo-op))
(setf (gethash "[bits"              *emit-function-hash-table-x64*) (list #'bits-pseudo-op))
(setf (gethash "global"             *emit-function-hash-table-x64*) (list #'global-pseudo-op))
(setf (gethash "section"            *emit-function-hash-table-x64*) (list #'section-pseudo-op))
;;; segment registers.
(setf (gethash "cs:"                *emit-function-hash-table-x64*) (list #'cs-x86))
(setf (gethash "ds:"                *emit-function-hash-table-x64*) (list #'ds-x86))
(setf (gethash "es:"                *emit-function-hash-table-x64*) (list #'es-x86))
(setf (gethash "fs:"                *emit-function-hash-table-x64*) (list #'fs-x86))
(setf (gethash "gs:"                *emit-function-hash-table-x64*) (list #'gs-x86))
(setf (gethash "ss:"                *emit-function-hash-table-x64*) (list #'ss-x86))

;;; instructions in alphabetical order.
(setf (gethash "adc"                *emit-function-hash-table-x64*) (list #'adc-x64 #'adc-reg-rm-x64 #'adc-rm-reg-x64))
(setf (gethash "adc-reg-rm"         *emit-function-hash-table-x64*) (list #'adc-reg-rm-x64))
(setf (gethash "adc-rm-reg"         *emit-function-hash-table-x64*) (list #'adc-rm-reg-x64))
(setf (gethash "add"                *emit-function-hash-table-x64*) (list #'add-x64 #'add-reg-rm-x64 #'add-rm-reg-x64))
(setf (gethash "add-reg-rm"         *emit-function-hash-table-x64*) (list #'add-reg-rm-x64))
(setf (gethash "add-rm-reg"         *emit-function-hash-table-x64*) (list #'add-rm-reg-x64))
(setf (gethash "and"                *emit-function-hash-table-x64*) (list #'and-x64 #'and-reg-rm-x64 #'and-rm-reg-x64))
(setf (gethash "and-reg-rm"         *emit-function-hash-table-x64*) (list #'and-reg-rm-x64))
(setf (gethash "and-rm-reg"         *emit-function-hash-table-x64*) (list #'and-rm-reg-x64))
(setf (gethash "call"               *emit-function-hash-table-x64*) (list #'call-x64))
(setf (gethash "cbw"                *emit-function-hash-table-x64*) (list #'cbw-x32-x64))
(setf (gethash "cdq"                *emit-function-hash-table-x64*) (list #'cdq-x32-x64))
(setf (gethash "cdqe"               *emit-function-hash-table-x64*) (list #'cdqe-x64))
(setf (gethash "clc"                *emit-function-hash-table-x64*) (list #'clc-x86))
(setf (gethash "cld"                *emit-function-hash-table-x64*) (list #'cld-x86))
(setf (gethash "cli"                *emit-function-hash-table-x64*) (list #'cli-x86))
(setf (gethash "cmc"                *emit-function-hash-table-x64*) (list #'cmc-x86))
(setf (gethash "cmp"                *emit-function-hash-table-x64*) (list #'cmp-x64 #'cmp-reg-rm-x64 #'cmp-rm-reg-x64))
(setf (gethash "cmp-reg-rm"         *emit-function-hash-table-x64*) (list #'cmp-reg-rm-x64))
(setf (gethash "cmp-rm-reg"         *emit-function-hash-table-x64*) (list #'cmp-rm-reg-x64))
(setf (gethash "cmpsb"              *emit-function-hash-table-x64*) (list #'cmpsb-x86))
(setf (gethash "cmpsd"              *emit-function-hash-table-x64*) (list #'cmpsd-x32-x64))
(setf (gethash "cmpsq"              *emit-function-hash-table-x64*) (list #'cmpsq-48-x64 #'cmpsq-49-x64 #'cmpsq-4a-x64 #'cmpsq-4b-x64 #'cmpsq-4c-x64 #'cmpsq-4d-x64 #'cmpsq-4e-x64 #'cmpsq-4f-x64))
(setf (gethash "cmpsw"              *emit-function-hash-table-x64*) (list #'cmpsw-x86))
(setf (gethash "cwd"                *emit-function-hash-table-x64*) (list #'cwd-x32-x64))
(setf (gethash "cwde"               *emit-function-hash-table-x64*) (list #'cwde-x32-x64))
(setf (gethash "dec"                *emit-function-hash-table-x64*) (list #'dec-x64))
(setf (gethash "f2xm1"              *emit-function-hash-table-x64*) (list #'f2xm1-x87))
(setf (gethash "fabs"               *emit-function-hash-table-x64*) (list #'fabs-x87))
(setf (gethash "fchs"               *emit-function-hash-table-x64*) (list #'fchs-x87))
(setf (gethash "fclex"              *emit-function-hash-table-x64*) (list #'fclex-x87))
(setf (gethash "fnclex"             *emit-function-hash-table-x64*) (list #'fnclex-x87))
(setf (gethash "fcos"               *emit-function-hash-table-x64*) (list #'fcos-x87))
(setf (gethash "fdecstp"            *emit-function-hash-table-x64*) (list #'fdecstp-x87))
(setf (gethash "fincstp"            *emit-function-hash-table-x64*) (list #'fincstp-x87))
(setf (gethash "finit"              *emit-function-hash-table-x64*) (list #'finit-x87))
(setf (gethash "fld1"               *emit-function-hash-table-x64*) (list #'fld1-x87))
(setf (gethash "fldl2e"             *emit-function-hash-table-x64*) (list #'fldl2e-x87))
(setf (gethash "fldl2t"             *emit-function-hash-table-x64*) (list #'fldl2t-x87))
(setf (gethash "fldlg2"             *emit-function-hash-table-x64*) (list #'fldlg2-x87))
(setf (gethash "fldln2"             *emit-function-hash-table-x64*) (list #'fldln2-x87))
(setf (gethash "fldpi"              *emit-function-hash-table-x64*) (list #'fldpi-x87))
(setf (gethash "fldz"               *emit-function-hash-table-x64*) (list #'fldz-x87))
(setf (gethash "fninit"             *emit-function-hash-table-x64*) (list #'fninit-x87))
(setf (gethash "fnop"               *emit-function-hash-table-x64*) (list #'fnop-x87))
(setf (gethash "fpatan"             *emit-function-hash-table-x64*) (list #'fpatan-x87))
(setf (gethash "fprem"              *emit-function-hash-table-x64*) (list #'fprem-x87))
(setf (gethash "fprem1"             *emit-function-hash-table-x64*) (list #'fprem1-x87))
(setf (gethash "fptan"              *emit-function-hash-table-x64*) (list #'fptan-x87))
(setf (gethash "frndint"            *emit-function-hash-table-x64*) (list #'frndint-x87))
(setf (gethash "fscale"             *emit-function-hash-table-x64*) (list #'fscale-x87))
(setf (gethash "fsin"               *emit-function-hash-table-x64*) (list #'fsin-x87))
(setf (gethash "fsincos"            *emit-function-hash-table-x64*) (list #'fsincos-x87))
(setf (gethash "fsqrt"              *emit-function-hash-table-x64*) (list #'fsqrt-x87))
(setf (gethash "ftst"               *emit-function-hash-table-x64*) (list #'ftst-x87))
(setf (gethash "fxam"               *emit-function-hash-table-x64*) (list #'fxam-x87))
(setf (gethash "fxtract"            *emit-function-hash-table-x64*) (list #'fxtract-x87))
(setf (gethash "fyl2x"              *emit-function-hash-table-x64*) (list #'fyl2x-x87))
(setf (gethash "fyl2xp1"            *emit-function-hash-table-x64*) (list #'fyl2xp1-x87))
(setf (gethash "hlt"                *emit-function-hash-table-x64*) (list #'hlt-x86))
(setf (gethash "in"                 *emit-function-hash-table-x64*) (list #'in-x32-x64))
(setf (gethash "inc"                *emit-function-hash-table-x64*) (list #'inc-x64))
(setf (gethash "insb"               *emit-function-hash-table-x64*) (list #'insb-x86))
(setf (gethash "insd"               *emit-function-hash-table-x64*) (list #'insd-x32-x64))
(setf (gethash "insw"               *emit-function-hash-table-x64*) (list #'insw-x86))
(setf (gethash "iret"               *emit-function-hash-table-x64*) (list #'iret-x86))
(setf (gethash "jmp"                *emit-function-hash-table-x64*) (list #'jmp-x64))
(setf (gethash "jmp-rel8"           *emit-function-hash-table-x64*) (list #'jmp-rel8-x86))
(setf (gethash "ja-rel8"            *emit-function-hash-table-x64*) (list #'ja-rel8-x86))
(setf (gethash "jae-rel8"           *emit-function-hash-table-x64*) (list #'jae-rel8-x86))
(setf (gethash "jb-rel8"            *emit-function-hash-table-x64*) (list #'jb-rel8-x86))
(setf (gethash "jb-rel8"            *emit-function-hash-table-x64*) (list #'jb-rel8-x86))
(setf (gethash "jbe-rel8"           *emit-function-hash-table-x64*) (list #'jbe-rel8-x86))
(setf (gethash "jc-rel8"            *emit-function-hash-table-x64*) (list #'jc-rel8-x86))
(setf (gethash "je-rel8"            *emit-function-hash-table-x64*) (list #'je-rel8-x86))
(setf (gethash "jecxz-rel8"         *emit-function-hash-table-x64*) (list #'jecxz-rel8-x32-x64))
(setf (gethash "jg-rel8"            *emit-function-hash-table-x64*) (list #'jg-rel8-x86))
(setf (gethash "jge-rel8"           *emit-function-hash-table-x64*) (list #'jge-rel8-x86))
(setf (gethash "jl-rel8"            *emit-function-hash-table-x64*) (list #'jl-rel8-x86))
(setf (gethash "jle-rel8"           *emit-function-hash-table-x64*) (list #'jle-rel8-x86))
(setf (gethash "jna-rel8"           *emit-function-hash-table-x64*) (list #'jna-rel8-x86))
(setf (gethash "jnae-rel8"          *emit-function-hash-table-x64*) (list #'jnae-rel8-x86))
(setf (gethash "jnb-rel8"           *emit-function-hash-table-x64*) (list #'jnb-rel8-x86))
(setf (gethash "jnbe-rel8"          *emit-function-hash-table-x64*) (list #'jnbe-rel8-x86))
(setf (gethash "jnc-rel8"           *emit-function-hash-table-x64*) (list #'jnc-rel8-x86))
(setf (gethash "jne-rel8"           *emit-function-hash-table-x64*) (list #'jne-rel8-x86))
(setf (gethash "jng-rel8"           *emit-function-hash-table-x64*) (list #'jng-rel8-x86))
(setf (gethash "jnge-rel8"          *emit-function-hash-table-x64*) (list #'jnge-rel8-x86))
(setf (gethash "jnl-rel8"           *emit-function-hash-table-x64*) (list #'jnl-rel8-x86))
(setf (gethash "jnle-rel8"          *emit-function-hash-table-x64*) (list #'jnle-rel8-x86))
(setf (gethash "jno-rel8"           *emit-function-hash-table-x64*) (list #'jno-rel8-x86))
(setf (gethash "jnp-rel8"           *emit-function-hash-table-x64*) (list #'jnp-rel8-x86))
(setf (gethash "jns-rel8"           *emit-function-hash-table-x64*) (list #'jns-rel8-x86))
(setf (gethash "jnz-rel8"           *emit-function-hash-table-x64*) (list #'jnz-rel8-x86))
(setf (gethash "jo-rel8"            *emit-function-hash-table-x64*) (list #'jo-rel8-x86))
(setf (gethash "jp-rel8"            *emit-function-hash-table-x64*) (list #'jp-rel8-x86))
(setf (gethash "jpe-rel8"           *emit-function-hash-table-x64*) (list #'jpe-rel8-x86))
(setf (gethash "jpo-rel8"           *emit-function-hash-table-x64*) (list #'jpo-rel8-x86))
(setf (gethash "jrcxz-rel8"         *emit-function-hash-table-x64*) (list #'jrcxz-rel8-x64))
(setf (gethash "js-rel8"            *emit-function-hash-table-x64*) (list #'js-rel8-x86))
(setf (gethash "jz-rel8"            *emit-function-hash-table-x64*) (list #'jz-rel8-x86))
(setf (gethash "lea"                *emit-function-hash-table-x64*) (list #'lea-x64))
(setf (gethash "leave"              *emit-function-hash-table-x64*) (list #'leave-x86))
(setf (gethash "lodsb"              *emit-function-hash-table-x64*) (list #'lodsb-x86))
(setf (gethash "lodsd"              *emit-function-hash-table-x64*) (list #'lodsd-x32-x64))
(setf (gethash "lodsq"              *emit-function-hash-table-x64*) (list #'lodsq-48-x64 #'lodsq-49-x64 #'lodsq-4a-x64 #'lodsq-4b-x64 #'lodsq-4c-x64 #'lodsq-4d-x64 #'lodsq-4e-x64 #'lodsq-4f-x64))
(setf (gethash "lodsw"              *emit-function-hash-table-x64*) (list #'lodsw-x86))
(setf (gethash "neg"                *emit-function-hash-table-x64*) (list #'neg-x64))
(setf (gethash "nop"                *emit-function-hash-table-x64*) (list #'nop-x86))
(setf (gethash "not"                *emit-function-hash-table-x64*) (list #'not-x64))
(setf (gethash "or"                 *emit-function-hash-table-x64*) (list #'or-x64 #'or-reg-rm-x64 #'or-rm-reg-x64))
(setf (gethash "or-reg-rm"          *emit-function-hash-table-x64*) (list #'or-reg-rm-x64))
(setf (gethash "or-rm-reg"          *emit-function-hash-table-x64*) (list #'or-rm-reg-x64))
(setf (gethash "rcl-1"              *emit-function-hash-table-x64*) (list #'rcl-1-x64))
(setf (gethash "rcl-cl"             *emit-function-hash-table-x64*) (list #'rcl-cl-x64))
(setf (gethash "rcr-1"              *emit-function-hash-table-x64*) (list #'rcr-1-x64))
(setf (gethash "rcr-cl"             *emit-function-hash-table-x64*) (list #'rcr-cl-x64))
(setf (gethash "rol-1"              *emit-function-hash-table-x64*) (list #'rol-1-x64))
(setf (gethash "rol-cl"             *emit-function-hash-table-x64*) (list #'rol-cl-x64))
(setf (gethash "ror-1"              *emit-function-hash-table-x64*) (list #'ror-1-x64))
(setf (gethash "ror-cl"             *emit-function-hash-table-x64*) (list #'ror-cl-x64))
(setf (gethash "sal-1"              *emit-function-hash-table-x64*) (list #'shl-1-x64))
(setf (gethash "sal-cl"             *emit-function-hash-table-x64*) (list #'shl-cl-x64))
(setf (gethash "sar-1"              *emit-function-hash-table-x64*) (list #'sar-1-x64))
(setf (gethash "sar-cl"             *emit-function-hash-table-x64*) (list #'sar-cl-x64))
(setf (gethash "shl-1"              *emit-function-hash-table-x64*) (list #'shl-1-x64))
(setf (gethash "shl-cl"             *emit-function-hash-table-x64*) (list #'shl-cl-x64))
(setf (gethash "shr-1"              *emit-function-hash-table-x64*) (list #'shr-1-x64))
(setf (gethash "shr-cl"             *emit-function-hash-table-x64*) (list #'shr-cl-x64))
(setf (gethash "out"                *emit-function-hash-table-x64*) (list #'out-x32-x64))
(setf (gethash "outsb"              *emit-function-hash-table-x64*) (list #'outsb-x86))
(setf (gethash "outsd"              *emit-function-hash-table-x64*) (list #'outsd-x32-x64))
(setf (gethash "outsw"              *emit-function-hash-table-x64*) (list #'outsw-x86))
(setf (gethash "pop"                *emit-function-hash-table-x64*) (list #'pop-x64))
(setf (gethash "push"               *emit-function-hash-table-x64*) (list #'push-x64))
(setf (gethash "ret"                *emit-function-hash-table-x64*) (list #'ret-x86))
(setf (gethash "sbb"                *emit-function-hash-table-x64*) (list #'sbb-x64 #'sbb-reg-rm-x64 #'sbb-rm-reg-x64))
(setf (gethash "sbb-reg-rm"         *emit-function-hash-table-x64*) (list #'sbb-reg-rm-x64))
(setf (gethash "sbb-rm-reg"         *emit-function-hash-table-x64*) (list #'sbb-rm-reg-x64))
(setf (gethash "scasb"              *emit-function-hash-table-x64*) (list #'scasb-x86))
(setf (gethash "scasd"              *emit-function-hash-table-x64*) (list #'scasd-x32-x64))
(setf (gethash "scasq"              *emit-function-hash-table-x64*) (list #'scasq-48-x64 #'scasq-49-x64 #'scasq-4a-x64 #'scasq-4b-x64 #'scasq-4c-x64 #'scasq-4d-x64 #'scasq-4e-x64 #'scasq-4f-x64))
(setf (gethash "scasw"              *emit-function-hash-table-x64*) (list #'scasw-x86))
(setf (gethash "stc"                *emit-function-hash-table-x64*) (list #'stc-x86))
(setf (gethash "std"                *emit-function-hash-table-x64*) (list #'std-x86))
(setf (gethash "sti"                *emit-function-hash-table-x64*) (list #'sti-x86))
(setf (gethash "stosb"              *emit-function-hash-table-x64*) (list #'stosb-x86))
(setf (gethash "stosd"              *emit-function-hash-table-x64*) (list #'stosd-x32-x64))
(setf (gethash "stosq"              *emit-function-hash-table-x64*) (list #'stosq-48-x64 #'stosq-49-x64 #'stosq-4a-x64 #'stosq-4b-x64 #'stosq-4c-x64 #'stosq-4d-x64 #'stosq-4e-x64 #'stosq-4f-x64))
(setf (gethash "stosw"              *emit-function-hash-table-x64*) (list #'stosw-x86))
(setf (gethash "sub"                *emit-function-hash-table-x64*) (list #'sub-x64 #'sub-reg-rm-x64 #'sub-rm-reg-x64))
(setf (gethash "sub-reg-rm"         *emit-function-hash-table-x64*) (list #'sub-reg-rm-x64))
(setf (gethash "sub-rm-reg"         *emit-function-hash-table-x64*) (list #'sub-rm-reg-x64))
(setf (gethash "syscall"            *emit-function-hash-table-x64*) (list #'syscall-x64))
(setf (gethash "mov"                *emit-function-hash-table-x64*) (list #'mov-x64 #'mov-reg-rm-x64 #'mov-rm-reg-x64))
(setf (gethash "mov-reg-rm"         *emit-function-hash-table-x64*) (list #'mov-reg-rm-x64))
(setf (gethash "mov-rm-reg"         *emit-function-hash-table-x64*) (list #'mov-rm-reg-x64))
(setf (gethash "movsb"              *emit-function-hash-table-x64*) (list #'movsb-x86))
(setf (gethash "movsd"              *emit-function-hash-table-x64*) (list #'movsd-x32-x64))
(setf (gethash "movsq"              *emit-function-hash-table-x64*) (list #'movsq-48-x64 #'movsq-49-x64 #'movsq-4a-x64 #'movsq-4b-x64 #'movsq-4c-x64 #'movsq-4d-x64 #'movsq-4e-x64 #'movsq-4f-x64))
(setf (gethash "movsw"              *emit-function-hash-table-x64*) (list #'movsw-x86))
(setf (gethash "xor"                *emit-function-hash-table-x64*) (list #'xor-x64 #'xor-reg-rm-x64 #'xor-rm-reg-x64))
(setf (gethash "xor-reg-rm"         *emit-function-hash-table-x64*) (list #'xor-reg-rm-x64))
(setf (gethash "xor-rm-reg"         *emit-function-hash-table-x64*) (list #'xor-rm-reg-x64))
